version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    networks:
      - g2net
    volumes:
      - .:/app
      - /app/node_modules  # Evita conflictos con node_modules del host
    environment:
      - CHOKIDAR_USEPOLLING=true  # Permite hot reload en Docker para Vite
    
networks:
  g2net:
    driver: bridge 